export const privacyData = {
  title: "Privacy Policy",
  companyName: "Zevitech",
  contactEmail: "support@zevitech.com",
  sections: [
    {
      id: "introduction",
      title: "Introduction",
      content: [
        "Zevitech (“we,” “our,” “us”) respects your privacy and is committed to protecting your personal and business information.",
        "This Privacy Policy explains how we collect, use, store, and protect information when you use our website or engage our services.",
        "By using our website or services, you agree to this Privacy Policy.",
      ],
    },
    {
      id: "data-collected",
      title: "Information We Collect",
      content: [
        "We may collect the following types of information:",
        "A. Personal Information",
        "• Full name",
        "• Email address",
        "• Phone number",
        "• Mailing address",
        "• Business information",
        "B. Service-Related Information",
        "• Information required for requested services",
        "• Documents voluntarily submitted by clients",
        "• Application or registration-related details",
        "C. Technical Information",
        "• IP address",
        "• Browser type",
        "• Device information",
        "• Website usage data through analytics tools",
      ],
    },
    {
      id: "information-we-do-not-collect",
      title: "Information We Do Not Collect",
      content: [
        "Zevitech does not request or collect:",
        "• Banking passwords",
        "• One-time passwords (OTPs)",
        "• Online banking login credentials",
        "• Unrelated financial authentication information",
        "Payment processing is conducted through secure and authorized merchant systems.",
      ],
    },
    {
      id: "purpose-of-collection",
      title: "Purpose of Information Collection",
      content: [
        "We collect information solely for:",
        "• Providing requested services",
        "• Preparing and coordinating documentation",
        "• Communicating with clients",
        "• Processing payments",
        "• Internal recordkeeping",
        "• Legal and compliance obligations",
        "We do not sell personal information.",
      ],
    },
    {
      id: "third-party-sharing",
      title: "Third-Party Sharing",
      content: [
        "Information may be shared with third parties only when necessary to perform requested services, including:",
        "• Government filing systems",
        "• Registered agents",
        "• Licensed professionals",
        "• Partner service providers operating under structured agreements",
        "• Payment processing providers",
        "Information shared is limited strictly to what is required for service execution.",
      ],
    },
    {
      id: "payment-processing",
      title: "Payment Processing",
      content: [
        "Payments are processed through secure third-party payment processors.",
        "Zevitech does not store full credit card details on its servers.",
        "All transactions are subject to the security standards of the payment processor used.",
      ],
    },
    {
      id: "data-security",
      title: "Data Security",
      content: [
        "We implement reasonable administrative and technical safeguards to protect client information from unauthorized access, disclosure, or misuse.",
        "While we take appropriate security measures, no method of transmission over the internet can be guaranteed to be completely secure.",
      ],
    },
    {
      id: "data-retention",
      title: "Data Retention",
      content: [
        "We retain information only as long as necessary for:",
        "• Completion of services",
        "• Recordkeeping",
        "• Compliance with applicable laws",
        "Information is not retained longer than reasonably required.",
      ],
    },
    {
      id: "client-rights",
      title: "Client Rights",
      content: [
        "Clients may request:",
        "• Access to their personal information",
        "• Correction of inaccurate information",
        "• Deletion of information where legally permissible",
        "Requests can be submitted through our official contact channels listed on our website.",
      ],
    },
    {
      id: "cookies-analytics",
      title: "Cookies & Analytics",
      content: [
        "Our website may use cookies and analytics tools to improve user experience and monitor website performance.",
        "Users may control cookie preferences through their browser settings.",
      ],
    },
    {
      id: "policy-updates",
      title: "Policy Updates",
      content: [
        "Zevitech reserves the right to update this Privacy Policy at any time. Updated versions will be published on this page.",
      ],
    },
    {
      id: "contact",
      title: "Contact Us",
      content: [
        "If you have questions or concerns about this Privacy Policy, please contact:",
        "Zevitech",
        "📧 support@zevitech.com",
      ],
    },
  ],
};
