export const shopifyPackages = [
  {
    id: "basic",
    name: "Basic Launch",
    price: "$299",
    highlight: false,
    badge: null,
  },
  {
    id: "business",
    name: "Business Starter",
    price: "$599",
    highlight: false,
    badge: null,
  },
  {
    id: "pro",
    name: "Pro Seller",
    price: "$899",
    highlight: true,
    badge: "Best Selling",
  },
  {
    id: "brand",
    name: "Brand Empire",
    price: "$1399",
    highlight: false,
    badge: "Top Performer",
  },
];

export const shopifyFeatures = [
  {
    category: "Features",
    items: [
      {
        name: "Shopify Theme Setup",
        basic: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Mobile Responsive Design",
        basic: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Number of Products Added",
        basic: "Up to 10",
        business: "Up to 25",
        pro: "Up to 50",
        brand: "Up to 100",
      },
      {
        name: "Basic Navigation/Menu Setup",
        basic: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Home, Product, About, Contact Pages",
        basic: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Premium Theme Customization",
        basic: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Newsletter Popup Setup",
        basic: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Trust Badges & Conversion Elements",
        basic: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Collection & Category Setup",
        basic: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Policy Pages (Refund, Shipping, Privacy, etc.)",
        basic: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Basic On-Page SEO",
        basic: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Advanced SEO Optimization",
        basic: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Branding Integration (Colors, Fonts, Logo)",
        basic: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Homepage Copywriting",
        basic: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Product Page Optimization",
        basic: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Premium Apps Integration (Reviews, Upsells, etc.)",
        basic: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Abandoned Cart Recovery Setup",
        basic: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Blog Setup",
        basic: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Social Media Integration",
        basic: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Email Marketing Integration (Klaviyo, Mailchimp)",
        basic: false,
        business: false,
        pro: false,
        brand: true,
      },
      {
        name: "Custom Banner & Graphic Design",
        basic: false,
        business: false,
        pro: false,
        brand: true,
      },
      {
        name: "Copywriting for Top 5 Products",
        basic: false,
        business: false,
        pro: false,
        brand: true,
      },
      {
        name: "Landing Page for Ads",
        basic: false,
        business: false,
        pro: false,
        brand: true,
      },
      {
        name: "Store Speed Optimization",
        basic: false,
        business: false,
        pro: false,
        brand: true,
      },
      {
        name: "Funnel / Upsell Setup",
        basic: false,
        business: false,
        pro: false,
        brand: true,
      },
      {
        name: "Facebook Pixel + Google Analytics Setup",
        basic: false,
        business: false,
        pro: false,
        brand: true,
      },
      {
        name: "Revisions Included",
        basic: "1 Round",
        business: "2 Rounds",
        pro: "3 Rounds",
        brand: "4 Rounds",
      },
      {
        name: "Post-Launch Support",
        basic: false,
        business: false,
        pro: false,
        brand: "15 Days",
      },
    ],
  },
];

export const twoDLogoPackages = [
  {
    id: "starter",
    name: "Starter",
    price: "$99",
    highlight: false,
    badge: null,
  },
  {
    id: "business",
    name: "Business",
    price: "$199",
    highlight: false,
    badge: null,
  },
  {
    id: "pro",
    name: "Pro",
    price: "$399",
    highlight: true,
    badge: "Most Popular",
  },
  {
    id: "brand",
    name: "Brand Empire",
    price: "$699",
    highlight: false,
    badge: "Premium",
  },
];

export const twoDLogoFeatures = [
  {
    category: "2D Logo Design Packages",
    items: [
      {
        name: "2D Logo Concepts",
        starter: 2,
        business: 4,
        pro: 6,
        brand: 10,
      },
      {
        name: "Revisions Included",
        starter: "2 Rounds",
        business: "4 Rounds",
        pro: "6 Rounds",
        brand: "Unlimited",
      },
      {
        name: "File Formats (JPG, PNG)",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Vector File (AI, EPS)",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "High-Resolution Files",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Transparent Background",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Source File Included",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Social Media Kit",
        starter: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Stationery Design (Business Card, Letterhead)",
        starter: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Brand Guidelines PDF",
        starter: false,
        business: false,
        pro: false,
        brand: true,
      },
      {
        name: "Dedicated Designer",
        starter: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Delivery Time",
        starter: "3 Days",
        business: "5 Days",
        pro: "7 Days",
        brand: "10 Days",
      },
      {
        name: "Post-Delivery Support",
        starter: false,
        business: false,
        pro: "7 Days",
        brand: "15 Days",
      },
    ],
  },
];

export const logo3DDesignPackages = [
  {
    id: "starter",
    name: "Starter",
    price: "$149",
    highlight: false,
    badge: null,
  },
  {
    id: "business",
    name: "Business",
    price: "$299",
    highlight: false,
    badge: null,
  },
  {
    id: "pro",
    name: "Pro",
    price: "$499",
    highlight: true,
    badge: "Most Popular",
  },
  {
    id: "brand",
    name: "Brand Empire",
    price: "$899",
    highlight: false,
    badge: "Best Value",
  },
];

export const logo3DDesignFeatures = [
  {
    category: "Logo Design Features",
    items: [
      {
        name: "3D Logo Concepts",
        starter: 3,
        business: 4,
        pro: 5,
        brand: 8,
      },
      {
        name: "Revisions Included",
        starter: "2 Rounds",
        business: "4 Rounds",
        pro: "6 Rounds",
        brand: "Unlimited",
      },
      {
        name: "File Formats (JPG, PNG)",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Vector File (AI, EPS)",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "High-Resolution Files",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Transparent Background",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "3D Mockups",
        starter: 1,
        business: 2,
        pro: 3,
        brand: 5,
      },
      {
        name: "Source File Included",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Social Media Kit",
        starter: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Stationery Design (Business Card, Letterhead)",
        starter: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Brand Guidelines PDF",
        starter: false,
        business: false,
        pro: false,
        brand: true,
      },
      {
        name: "Delivery Time",
        starter: "5 Days",
        business: "7 Days",
        pro: "10 Days",
        brand: "12 Days",
      },
      {
        name: "Post-Delivery Support",
        starter: false,
        business: false,
        pro: "7 Days",
        brand: "15 Days",
      },
    ],
  },
];

export const animatedLogoPackages = [
  {
    id: "starter",
    name: "Starter",
    price: "$199",
    highlight: false,
    badge: null,
  },
  {
    id: "business",
    name: "Business",
    price: "$399",
    highlight: false,
    badge: null,
  },
  {
    id: "pro",
    name: "Pro",
    price: "$699",
    highlight: true,
    badge: "Most Popular",
  },
  {
    id: "brand",
    name: "Brand Empire",
    price: "$1199",
    highlight: false,
    badge: "Premium",
  },
];

export const animatedLogoFeatures = [
  {
    category: "Animated Logo Design Features",
    items: [
      {
        name: "Animation Styles",
        starter: "Basic Motion",
        business: "Smooth Motion",
        pro: "Advanced Motion",
        brand: "Custom Effects",
      },
      {
        name: "Logo Concepts",
        starter: 1,
        business: 2,
        pro: 3,
        brand: 5,
      },
      {
        name: "Revisions Included",
        starter: "1 Round",
        business: "3 Rounds",
        pro: "5 Rounds",
        brand: "Unlimited",
      },
      {
        name: "File Formats (MP4, GIF)",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Transparent Background",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Sound Effects",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Source File (After Effects/AE)",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Social Media Ready Versions",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Delivery Time",
        starter: "5 Days",
        business: "7 Days",
        pro: "10 Days",
        brand: "15 Days",
      },
      {
        name: "Post-Delivery Support",
        starter: false,
        business: false,
        pro: "7 Days",
        brand: "15 Days",
      },
    ],
  },
];

export const customizedLogoPackages = [
  {
    id: "starter",
    name: "Starter",
    price: "$299",
    highlight: false,
    badge: null,
  },
  {
    id: "business",
    name: "Business",
    price: "$499",
    highlight: false,
    badge: null,
  },
  {
    id: "pro",
    name: "Pro",
    price: "$799",
    highlight: true,
    badge: "Most Popular",
  },
  {
    id: "brand",
    name: "Brand Empire",
    price: "$1499",
    highlight: false,
    badge: "Premium",
  },
];

export const customizedLogoFeatures = [
  {
    category: "Customized Logo Design Features",
    items: [
      {
        name: "Custom Concepts",
        starter: 2,
        business: 4,
        pro: 6,
        brand: 10,
      },
      {
        name: "Revisions Included",
        starter: "3 Rounds",
        business: "5 Rounds",
        pro: "7 Rounds",
        brand: "Unlimited",
      },
      {
        name: "File Formats (JPG, PNG)",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Vector File (AI, EPS)",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "High-Resolution Files",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Transparent Background",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Source File Included",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Brand Guidelines PDF",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Social Media Kit",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Stationery Design",
        starter: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Dedicated Designer",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Delivery Time",
        starter: "7 Days",
        business: "10 Days",
        pro: "12 Days",
        brand: "15 Days",
      },
      {
        name: "Post-Delivery Support",
        starter: false,
        business: "7 Days",
        pro: "10 Days",
        brand: "20 Days",
      },
    ],
  },
];

export const minimalLogoPackages = [
  {
    id: "starter",
    name: "Starter",
    price: "$79",
    highlight: false,
    badge: null,
  },
  {
    id: "business",
    name: "Business",
    price: "$149",
    highlight: false,
    badge: null,
  },
  {
    id: "pro",
    name: "Pro",
    price: "$299",
    highlight: true,
    badge: "Most Popular",
  },
  {
    id: "brand",
    name: "Brand Empire",
    price: "$499",
    highlight: false,
    badge: "Premium",
  },
];

export const minimalLogoFeatures = [
  {
    category: "Minimal Logo Design Packages",
    items: [
      {
        name: "Minimal Concepts",
        starter: 2,
        business: 4,
        pro: 6,
        brand: 8,
      },
      {
        name: "Revisions Included",
        starter: "2 Rounds",
        business: "4 Rounds",
        pro: "6 Rounds",
        brand: "Unlimited",
      },
      {
        name: "File Formats (JPG, PNG)",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Vector File (AI, EPS)",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "High-Resolution Files",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Transparent Background",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Source File Included",
        starter: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Brand Guidelines PDF",
        starter: false,
        business: false,
        pro: false,
        brand: true,
      },
      {
        name: "Delivery Time",
        starter: "2 Days",
        business: "3 Days",
        pro: "5 Days",
        brand: "7 Days",
      },
    ],
  },
];

export const mascotLogoPackages = [
  {
    id: "starter",
    name: "Starter",
    price: "$249",
    highlight: false,
    badge: null,
  },
  {
    id: "business",
    name: "Business",
    price: "$399",
    highlight: false,
    badge: null,
  },
  {
    id: "pro",
    name: "Pro",
    price: "$699",
    highlight: true,
    badge: "Most Popular",
  },
  {
    id: "brand",
    name: "Brand Empire",
    price: "$1199",
    highlight: false,
    badge: "Premium",
  },
];

export const mascotLogoFeatures = [
  {
    category: "Mascot Logo Design Packages",
    items: [
      {
        name: "Mascot Concepts",
        starter: 1,
        business: 2,
        pro: 3,
        brand: 6,
      },
      {
        name: "Revisions Included",
        starter: "2 Rounds",
        business: "4 Rounds",
        pro: "6 Rounds",
        brand: "Unlimited",
      },
      {
        name: "File Formats (JPG, PNG)",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Vector File (AI, EPS)",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "High-Resolution Files",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Transparent Background",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Full-Body Mascot",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Multiple Poses",
        starter: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Social Media Kit",
        starter: false,
        business: false,
        pro: false,
        brand: true,
      },
      {
        name: "Brand Guidelines PDF",
        starter: false,
        business: false,
        pro: false,
        brand: true,
      },
      {
        name: "Delivery Time",
        starter: "7 Days",
        business: "10 Days",
        pro: "12 Days",
        brand: "15 Days",
      },
    ],
  },
];

export const wordmarkLogoPackages = [
  {
    id: "starter",
    name: "Starter",
    price: "$99",
    highlight: false,
    badge: null,
  },
  {
    id: "business",
    name: "Business",
    price: "$199",
    highlight: false,
    badge: null,
  },
  {
    id: "pro",
    name: "Pro",
    price: "$399",
    highlight: true,
    badge: "Most Popular",
  },
  {
    id: "brand",
    name: "Brand Empire",
    price: "$699",
    highlight: false,
    badge: "Premium",
  },
];

export const wordmarkLogoFeatures = [
  {
    category: "Wordmark Logo Design Packages",
    items: [
      {
        name: "Wordmark Concepts",
        starter: 2,
        business: 4,
        pro: 6,
        brand: 8,
      },
      {
        name: "Revisions Included",
        starter: "2 Rounds",
        business: "4 Rounds",
        pro: "6 Rounds",
        brand: "Unlimited",
      },
      {
        name: "File Formats (JPG, PNG)",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Vector File (AI, EPS)",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "High-Resolution Files",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Transparent Background",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Font Licensing Guidance",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Source File Included",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Social Media Kit",
        starter: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Delivery Time",
        starter: "3 Days",
        business: "5 Days",
        pro: "7 Days",
        brand: "10 Days",
      },
    ],
  },
];

export const packagingDesignPackages = [
  {
    id: "starter",
    name: "Starter",
    price: "$199",
    highlight: false,
    badge: null,
  },
  {
    id: "business",
    name: "Business",
    price: "$399",
    highlight: false,
    badge: null,
  },
  {
    id: "pro",
    name: "Pro",
    price: "$699",
    highlight: true,
    badge: "Most Popular",
  },
  {
    id: "brand",
    name: "Brand Empire",
    price: "$1199",
    highlight: false,
    badge: "Premium",
  },
];

export const packagingDesignFeatures = [
  {
    category: "Product Packaging & Label Design Packages",
    items: [
      {
        name: "Packaging Concepts",
        starter: 1,
        business: 2,
        pro: 3,
        brand: 5,
      },
      {
        name: "Revisions Included",
        starter: "2 Rounds",
        business: "4 Rounds",
        pro: "6 Rounds",
        brand: "Unlimited",
      },
      {
        name: "Label Design",
        starter: 1,
        business: 2,
        pro: 3,
        brand: 5,
      },
      {
        name: "Mockups (3D/Product Display)",
        starter: 1,
        business: 2,
        pro: 3,
        brand: 5,
      },
      {
        name: "High-Resolution Print Files",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Die-Cut & Print-Ready Files",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Source Files (AI, PSD, EPS)",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Multiple Size Adaptations",
        starter: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Barcode/Ingredient Placement",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Brand Guidelines Alignment",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Delivery Time",
        starter: "5 Days",
        business: "7 Days",
        pro: "10 Days",
        brand: "15 Days",
      },
      {
        name: "Post-Delivery Support",
        starter: false,
        business: false,
        pro: "7 Days",
        brand: "15 Days",
      },
    ],
  },
];

export const socialMediaKitPackages = [
  {
    id: "starter",
    name: "Starter",
    price: "$99",
    highlight: false,
    badge: null,
  },
  {
    id: "business",
    name: "Business",
    price: "$199",
    highlight: false,
    badge: null,
  },
  {
    id: "pro",
    name: "Pro",
    price: "$399",
    highlight: true,
    badge: "Most Popular",
  },
  {
    id: "brand",
    name: "Brand Empire",
    price: "$699",
    highlight: false,
    badge: "Premium",
  },
];

export const socialMediaKitFeatures = [
  {
    category: "Social Media Kit Design Packages",
    items: [
      {
        name: "Profile Picture Design",
        starter: 1,
        business: 1,
        pro: 1,
        brand: 2,
      },
      {
        name: "Cover/Banner Design",
        starter: 1,
        business: 2,
        pro: 3,
        brand: 5,
      },
      {
        name: "Post Templates",
        starter: 3,
        business: 6,
        pro: 10,
        brand: 20,
      },
      {
        name: "Story Templates",
        starter: 2,
        business: 4,
        pro: 6,
        brand: 10,
      },
      {
        name: "Highlight Covers",
        starter: 3,
        business: 5,
        pro: 10,
        brand: 20,
      },
      {
        name: "File Formats (PNG, JPG)",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Editable Files (PSD/AI)",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Brand Consistency (Colors, Fonts)",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Platform Adaptations (FB, IG, X, LinkedIn)",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Delivery Time",
        starter: "3 Days",
        business: "5 Days",
        pro: "7 Days",
        brand: "10 Days",
      },
      {
        name: "Post-Delivery Support",
        starter: false,
        business: false,
        pro: "7 Days",
        brand: "15 Days",
      },
    ],
  },
];

export const brandIdentityPackages = [
  {
    id: "starter",
    name: "Starter",
    price: "$399",
    highlight: false,
    badge: null,
  },
  {
    id: "business",
    name: "Business",
    price: "$699",
    highlight: false,
    badge: null,
  },
  {
    id: "pro",
    name: "Pro",
    price: "$999",
    highlight: true,
    badge: "Most Popular",
  },
  {
    id: "brand",
    name: "Brand Empire",
    price: "$1799",
    highlight: false,
    badge: "Premium",
  },
];

export const brandIdentityFeatures = [
  {
    category: "Brand Identity Design Packages",
    items: [
      {
        name: "Brand Strategy Consultation",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Mood Board / Style Guide",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Logo Design (2D / Wordmark)",
        starter: "1 Concept",
        business: "2 Concepts",
        pro: "4 Concepts",
        brand: "6 Concepts",
      },
      {
        name: "Color Palette Development",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Typography Selection",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Business Card Design",
        starter: true,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Letterhead Design",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Envelope Design",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Social Media Kit (Profile, Cover, Post Templates)",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Email Signature Design",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Brand Guidelines PDF",
        starter: "5 Pages",
        business: "10 Pages",
        pro: "20 Pages",
        brand: "30 Pages",
      },
      {
        name: "Packaging Mockups",
        starter: false,
        business: false,
        pro: 2,
        brand: 4,
      },
      {
        name: "Stationery Set (Full Corporate Identity)",
        starter: false,
        business: false,
        pro: true,
        brand: true,
      },
      {
        name: "Dedicated Brand Designer",
        starter: false,
        business: true,
        pro: true,
        brand: true,
      },
      {
        name: "Delivery Time",
        starter: "7 Days",
        business: "10 Days",
        pro: "12 Days",
        brand: "15 Days",
      },
      {
        name: "Post-Delivery Support",
        starter: false,
        business: "7 Days",
        pro: "10 Days",
        brand: "20 Days",
      },
    ],
  },
];
